### ISSUE TITLE
Some observations.

### ISSUE THREAD

**Issue by Pinox** [Medtelligent/MT.MudBlazor.Extensions#5]
Thanks for lib.  Must say this lib functionality should have been standard in Mudblazor standard implementation. This works much better.

Just a couple of corrections.

1) Your DrawerTestPage.razor ( Docs on front page) does not include @inject IDrawerService DrawerService and it should otherwise code will give an instance error.

2) your example includes the following line :   
var drawer = DrawerService.Show<DrawerContent>("Test Drawer", new DrawerParameters().Add("Message", "Hello world!"), new DrawerOptions());   but there is no DrawerContent.  It should be "DrawersPane" as per your example.

3)          var drawer = DrawerService.Show<DrawersPane>("Test Drawer", new DrawerParameters().Add("Message", "Hello world!"), new 
            DrawerOptions() {  DisableOverlay = true , DisableBackdropClick = false , Color = Color.Info });

  When I use the above code the overlay is not active but the Backdropclick does not work if set to false.

**Comment by htapal** [comment]
Hi @Pinox!

Thank you for noticing the inconsistencies in the example.  I will address those.  I very much agree that this should've been standard in Mudblazor as well!

**Comment by htapal** [comment]
@Pinox, I've made the changes you pointed out!
